source 'https://rubygems.org'
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!


gem 'fastlane'
gem 'cocoapods'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
gem 'pod-builder'